### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by ttx**
Just for a test. Ignore me.

### CODE REVIEW

**Comment by openstack-gerrit** [comment]
Thank you for contributing to openstack/release-test!

openstack/release-test uses Gerrit for code review.

If you have never contributed to OpenStack before make sure you have read the
getting started documentation:
https://docs.openstack.org/infra/manual/developers.html#getting-started

Otherwise please visit
https://docs.openstack.org/infra/manual/developers.html#development-workflow
and follow the instructions there to upload your change to Gerrit.

**Comment by ttx** [comment]
Boo, you are fast.

**Comment by openstack-gerrit** [comment]
Thank you for contributing to openstack/release-test!

openstack/release-test uses Gerrit for code review.

If you have never contributed to OpenStack before make sure you have read the
getting started documentation:
https://docs.openstack.org/infra/manual/developers.html#getting-started

Otherwise please visit
https://docs.openstack.org/infra/manual/developers.html#development-workflow
and follow the instructions there to upload your change to Gerrit.

**Comment by ttx** [comment]
Every 5 minutes is fast

**Comment by openstack-gerrit** [comment]
Thank you for contributing to openstack/release-test!

openstack/release-test uses Gerrit for code review.

If you have never contributed to OpenStack before make sure you have read the
getting started documentation:
https://docs.openstack.org/infra/manual/developers.html#getting-started

Otherwise please visit
https://docs.openstack.org/infra/manual/developers.html#development-workflow
and follow the instructions there to upload your change to Gerrit.

**Comment by ttx** [comment]
I want this open for my test.

**Comment by ttx** [comment]
Thank you for your contribution!

This GitHub repository is just a mirror of https://opendev.org/openstack/release-test, where development
really happens. Pull requests proposed on GitHub are automatically closed.

If you are interested in pushing this code upstream, please note that
OpenStack development uses Gerrit for change proposal and code review.

If you have never contributed to OpenStack before, please see:
https://docs.opendev.org/opendev/infra-manual/latest/gettingstarted.html

Feel free to reach out on the #openstack-upstream-institute channel on
Freenode IRC in case you need help. You can access it through:
https://webchat.freenode.net/#openstack-upstream-institute

**Pull request closed without merging**
